linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dupl
    - errcheck
    # - funlen - TODO: enable it when golangci.com will support it.
    # - godox - TODO: enable it when golangci.com will support it.
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    # - whitespace - TODO: enable it when golangci.com will support it.

  # don't enable:
  # - depguard - until https://github.com/OpenPeeDeeP/depguard/issues/7 gets fixed
  # - maligned,prealloc
  # - gochecknoglobals

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: scale
      text: ".*"
    - path: types/int.go
      linters:
        - dupl
    - path: types/uint.go
      linters:
        - dupl
    - path: types/option_int.go
      linters:
        - dupl
    - path: types/option_uint.go
      linters:
        - dupl
    - path: types/data_test.go
      linters:
        - dupl
    - path: types/storage_data_raw_test.go
      linters:
        - dupl
    - path: doc.go
      linters:
        - lll
    - path: types/example_tuple_test.go
      linters:
        - lll
