version: "3.7"
services:
  substrate:
    image: parity/substrate:latest-v1.0
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    expose:
      - 9933
      - 9944
      - 30333
    networks:
      gsrpc-network:
        ipv4_address: 172.42.0.2
    command: --dev --ws-external --rpc-external
  gsrpc-test:
    build: .
    networks:
      gsrpc-network:
        ipv4_address: 172.42.0.99
    environment:
      - RPC_URL=http://172.42.0.2:9933
    volumes:
      - "$PWD/shared:/go/src/github.com/centrifuge/go-substrate-rpc-client/shared"
networks:
  gsrpc-network:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16
